# Файл docker-compose.yml

volumes:
  pg_data:
  static:

# Перечень контейнеров
services:
  db:
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data:/var/lib/postgresql/data
  # Имя и описание контейнера с бэкендом
  backend:
    # Из какого Dockerfile собирать образ для этого контейнера:
    image: demx88/taski_backend
    env_file: .env
    volumes:
      - static:/backend_static
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db
  # Имя третьего контейнера. Это контейнер с фронтендом
  frontend:
    env_file: .env
    image: demx88/taski_frontend
    volumes:
      - static:/frontend_static
    command: cp -r /app/build/. /frontend_static/
  # Добавляем новый контейнер: gateway
  gateway:
    # Сбилдить и запустить образ, 
    # описанный в Dockerfile в папке gateway
    image: demx88/taski_gateway
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера
    ports:
      - 8000:80
    volumes:
      - static:/staticfiles
    depends_on:
      - backend